[book]
title = "Rust By Example"
description = "Rust by Example (RBE) is a collection of runnable examples that illustrate various Rust concepts and standard libraries."
author = "The Rust Community"

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = true

[output.html.fold]
enable = true

[output.html]
# default-theme = "dark"
preferred-dark-theme = "navy"

git-repository-url = "https://github.com/goodsw4all/rust-by-example-ko"

[rust]
edition = "2021"
